# cargo-generate.toml

[template]
# 排除模板开发专用的文件，保持生成项目的纯净
exclude = ["cliff.toml", ".cursor/*"]

# 默认情况下不覆盖文件，更加安全。
# 如果确实需要覆盖，可以在运行时使用 `cargo generate --init` 参数。
init = false

[variables]
# 项目名称：自动从目录名获取，无需用户输入
project-name = { type = "string", prompt = false }

# 作者姓名：提示用户输入，并提供一个默认值
author = { type = "string", prompt = "What is your name?", default = "Paxon Qiao" }

# 作者邮箱：提示用户输入，并提供一个默认值
email = { type = "string", prompt = "What is your email?", default = "qiaopengjun0@gmail.com" }

# GitHub 用户名：提示用户输入，并提供一个默认值
github-username = { type = "string", prompt = "What is your GitHub username?", default = "qiaopengjun5162" }
